export const classes = {
  confirm: `
    inline-flex
    w-full
    justify-center
    rounded-md
    border
    border-transparent
    bg-green-600
    px-4
    py-2
    text-base
    font-medium
    text-white
    shadow-sm
    hover:bg-green-700
    focus:outline-none
    sm:ml-3
    sm:w-auto
    sm:text-sm`,
  dismiss: `
    mt-3
    inline-flex
    w-full
    justify-center
    rounded-md
    border
    border-gray-300
    bg-red-600
    px-4
    py-2
    text-base
    font-medium
    text-white
    shadow-sm
    hover:bg-red-700
    focus:outline-none
    sm:ml-3
    sm:mt-0
    sm:w-auto
    sm:text-sm`,
  footer: `
    border-t
    border-orange-100
    bg-orange-50
    p-2
    sm:flex
    sm:flex-row-reverse`,
}
