import { IProperty } from "./components/property-card";



export const akure_property :IProperty[] = [
    {
        id: "0",
        cover_image: "images/frame-15.png",
        property_name: "Olukayode Complex",
        description: "Oba Adesida roadOba Adesida roadOba Adesida roadOba Adesida roadOba Adesida roadOba Adesida roadOba Adesida roadOba Adesida roadOba Adesida roadOba Adesida roadOba Adesida road",
        price: 150000000,
        size: 1250,
        bdr: 5,
        btr: 4,
        action: "sale",
        address: "Oba Adesida road",
        agent: "Zalasoft",
        amenities: "Fenced, Gated",
    },
    {
        id: "1",
        cover_image: "images/frame-16.png",
        property_name: "RealPlus",
        description: "sdfghgfd",
        price: 1000000,
        size: 1250,
        bdr: 5,
        btr: 4,
        action: "rent",
        address: "Adj High Court",
        agent: "Faye Property",
        amenities: "Fenced, Gated",
    },
    {
        id: "2",
        cover_image: "images/frame-16.png",
        property_name: "RealPlus",
        description: "sdfghgfd",
        price: 1000000,
        size: 668.9,
        bdr: 5,
        btr: 4,
        action: "sale",
        address: "Adj High Court",
        agent: "Faye Property",
        amenities: "Fenced, Gated",
    },
    {
        id: "3",
        cover_image: "images/frame-16.png",
        property_name: "RayBus",
        description: "sdfghgfd",
        price: 1000000,
        size: 1250,
        bdr: 5,
        btr: 4,
        action: "invest",
        address: "Opp Mobil filling station, Arakale",
        agent: "Zalasoft",
        amenities: "Fenced, Gated",
    },
    {
        id: "4",
        cover_image: "images/frame-17.png",
        property_name: "RayBus",
        description: "sdfghgfd",
        price: 50000000,
        size: 1250,
        bdr: 5,
        btr: 4,
        action: "sale",
        address: "Opp Mobil filling station, Arakale",
        agent: "The King Condos",
        amenities: "Fenced, Gated",
    },
    {
        id: "5",
        cover_image: "images/frame-17.png",
        property_name: "Olukayode House",
        description: "sdfghgfd",
        price: 112000,
        size: 47,
        bdr: 2,
        btr: 1,
        action: "rent",
        address: "No.2, Oba Adesida road, Akure",
        agent: "Zalasoft",
        amenities: "floored compound, gated",
    },
]